export const SAMPLE_USER_INFO = {
  personalInfo: {
    firstName: "Godwin",
    lastName: "Benson",
    email: "busybenson@yahoo.com",
    phone: "2347083266188",
    preferredComms: { channel: "whatsapp", number: "2347083266188" },
  },
  profileInfo: {
    photo:
      "https://images.unsplash.com/photo-1502378735452-bc7d86632805?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&s=aa3a807e1bbdfd4364d1f449eaa96d82",
    video: "",
    description: "",
  },
  location: {
    address: "10 Lanre Awolokun Street, Gbagada",
    vicinity: "Agungi",
    region: "Lekki",
    state: "Abuja",
    country: "Nigeria",
  },
};

export const GROUPLESSON_DATA = {
  courseID: "IELTSProgram",
  hostID: "TuteriaHQ",
  hostName: "Tuteria",
  hostType: "Corporate",
  hostCountry: "Nigeria",
  timezone: "Africa/Lagos",
  VAT_CHARGE: 0,
  courseTitle: "How to get 8.0+ in IELTS and pass the exam at one attempt",
  courseSubtitle: "Most of our students score 7.5 - 9.0",
  courseBrief:
    "Tuteria's IELTS group class is like none other. We've helped the largest number of students pass the IELTS General Training, Academic and UKVI tests with many scoring between 7.5 - 9.0 in each section including first-time test takers and those re-taking the test. Join our class now and pass IELTS once and for all.",
  courseDescription:
    "IELTS is not your regular English Language exam. Its assesses your ability to Listen, Read, Write and Speak correctly in native English-speaking environments like the UK, Canada, Ireland etc., in order to determine if you'll be able to communicate, comprehend, survive and thrive in such environments.\nThis is why our classes are structured to ensure that you are well-prepared for the kinds of questions you'll be asked and how the IELTS examiners expect you to respond in order to pass the test and achieve your desired score.\nWe'll also help to correct fundamental weaknesses and incorrect usage of the English Language mostly due to our mother-tongue and environment we live in which may limit your overall performance. You'll also improve your skill in time management, attentiveness to detail, problem solving and organization which are all sub-skills tested in IELTS.\nOur world-class curriculum covers all 4 IELTS modules for both General Training and Academic tests with in-depth techniques taught by well-seasoned teachers. All students undertake a diagnostic test which helps us understand your strengths and weakness, as well as a standard IELTS Mock exam towards the end of the class. Join our class now before it's filled up.",
  courseContent: {
    visibility: "public",
    lessons: [
      {
        lessonTitle: "Writing Intro: Facts about the Writing Test",
        lessonSummary:
          "Students often have the most difficulty in Writing. In this lesson, we review how the Writing module is assessed, examine common question types and take a deep-dive into standard writing practices and skills needed for the best performance.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
      {
        lessonTitle: "Writing Tasks 1: Academic and General Writing",
        lessonSummary:
          "In this lesson, we'll learn and practice how to write formal, semi-formal and informal letters (IELTS General), as well as how to describe, summarize and interpret graphs, charts, tables, maps or diagrams (IELTS Academic). Students will know how to group information, paraphrase complex sentences, plan and organize write-ups following accepted rules for structure, grammar, paragraphing etc.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
      {
        lessonTitle: "Writing Tasks 2: Essay Writing",
        lessonSummary:
          "Here, we'll learn and practice the 6 types of essays including Causes and effects, Discussions, Advantages and disadvantages, Problems and solutions, Two-part questions and Opinions. Students will learn about topic sentences, how to develop supporting details, improving cohesion and developing winning essays.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
      {
        lessonTitle: "Reading Intro: Facts about the Reading Test",
        lessonSummary:
          "This is our first reading class! We'll review how the Reading module is assessed and familize students with all the question types asked in the test. Students will learn expert techniques to improve their speed, comprehension, vocabulary and time management to improve your score.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
      {
        lessonTitle: "Reading: How to Answer Reading Questions",
        lessonSummary:
          "The Reading module consists of 11 question types which include Matching Questions, Identifying Information, Multiple Choice, Sentence Completions, Diagram Labelling, Short Answer Questions etc. Students will have an in-depth understanding of each question type, and the principles for answering them correctly.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
      {
        lessonTitle: "Reading Conclusion & Introduction to Listening",
        lessonSummary:
          "We'll wrap up lessons on Reading and review the Listening module beginning with how the Listening test is assessed and its various questions types. Students will practice sharpening their listening ability and master proven success tips to keep in mind before, during and after listening test.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
      {
        lessonTitle: "Listening Tasks: Conversations and Discussions",
        lessonSummary:
          "In this lesson, we'll learn about Multiple choice, Form completion and Matching question types. Students will learn how to listen for numbers and synonyms of keywords, identifying paraphrases etc. We'll also learn how to respond to short answer questions and how to recognize different speakers.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
      {
        lessonTitle: "Listening Tasks: Monologues",
        lessonSummary:
          "We'll conclude the Listen module by learning about Sentence, Table and Note completion as well as develop skills on how to follow the speaker, how to listen for clues and signposts and how to recognize the speakers opinions and attitude which helps you answer questions correctly.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
      {
        lessonTitle: "Speaking: Interview, Talk and Discussion",
        lessonSummary:
          "In this class, we'll cover all aspects of the Speaking test such as the Interview part, the Individual Long Form and the Discussion part. In each part, we'll also learn how you'll be assessed and proven rules of grammar, fluency, vocabulary and pronunciation you should adhere to for best results.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
      {
        lessonTitle: "Mock Speaking Test",
        lessonSummary:
          "In this class, students undergo a Speaking mock test that simulates real-life exam conditions and receive instant feedback on how they have applied lessons learnt, how they performed and ways they can improve.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
      {
        lessonTitle: "Mock IELTS Test",
        lessonSummary:
          "We administer a standard IELTS Mock Test in Listening, Reading and Writing conducted under strict exam conditions.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
      {
        lessonTitle: "Mock Review & Correction",
        lessonSummary:
          "In this class, we provide comprehensive feedback on each student's performance on the Mock test, show corrections, respond to questions and discuss channels for providing further support.",
        lessonDescription: "",
        images: [],
        outcomes: [],
        activities: [],
        learningAids: [],
        requirements: [],
        projects: [],
      },
    ],
  },
  ageGroup: "Adult",
  category: "Test Prep",
  subcategory: "Test of English",
  relatedSubject: "IELTS",
  learningAids: {
    lessonPlan:
      "https://assets.ctfassets.net/tp6rlg4xcwsc/6erKGFLHRZkDxGFcSOyckC/afb3c9b64b2035c6c5f6b1faeb48a890/IELTS_Course_Handbook.pdf",
  },
  media: [],
  students: 1418,
  video: "https://youtu.be/LFl2wNkUKoM",
  rating: 4.9,
  ratingCount: 32,
  ratingPoints: {
    "Teaching style": 4.9,
    Knowledge: 5.0,
    Communication: 5.0,
    Engagement: 5.0,
    "Kept to Time": 4.9,
    "Great Value": 4.9,
  },
  learningOutcomes: [],
  upsell: {
    title: "IELTS Registration",
    relatedSubject: "IELTS",
    type: "Registration",
    description:
      "Add this if you want to register for IELTS. Tuteria will help process your registration in partnership with British Council or IDP. Our consultant will contact you shortly afterwards.",
    restrictedTo: ["Nigeria"],
    registration: [
      {
        option: "British Council",
        image:
          "https://thepienews.com/wp-content/uploads/2014/08/Screen-Shot-2014-08-12-at-12.40.45-860x375.png",
        price: 75000,
      },
      {
        option: "MOD IDP",
        image:
          "https://idp.ieltscanadatest.com/wp-content/themes/ilts/assets/images/footer-logo-new.png",
        price: 75000,
      },
    ],
  },
  mediums: [
    "Facebook",
    "Searched Online",
    "From a friend",
    "Instagram",
    "YouTube",
    "LinkedIn",
    "From a blog",
    "At an event",
    "Saw a banner",
    "None of these",
  ],
  results: {
    title: "Results from past students",
    description:
      "We help students get the best results. We identify each students' weak areas, and provide the knowledge, support, practice and confidence they need to aim high and score high. Their results prove that our process works.",
    passRate: 92,
    averageScore: 8.0,
    pictures: [
      {
        score: 8.5,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590797696/IMG-20191221-WA0001_pgi5mh.jpg",
        isPublic: true,
      },
      {
        score: 7.5,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796450/Picture5_pbc7lg.png",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796450/Picture6_zsydpo.png",
        isPublic: true,
      },
      {
        score: 7.5,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796450/Picture4_wmbvrm.png",
        isPublic: true,
      },
      {
        score: 7.5,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796450/Picture3_rsrvii.png",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796450/Picture1_m6avg5.png",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796449/IMG-20200321-WA0031_faku35.jpg",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796448/IMG-20190808-WA0018_xvfgov.jpg",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796449/IMG-20190808-WA0022_azhbhh.jpg",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796449/IMG-20190809-WA0012_hpxpxj.jpg",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796448/IMG-20190808-WA0028_tqxkwx.jpg",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796449/IMG-20190809-WA0010_gtbipc.jpg",
        isPublic: true,
      },
      {
        score: 7.5,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796448/IMG-20190808-WA0009_q5b8vy.jpg",
        isPublic: true,
      },
      {
        score: 7.5,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796448/IMG-20190808-WA0024_s2ek9g.jpg",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796448/IMG-20190808-WA0023_kxs2fp.jpg",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796448/IMG-20190808-WA0013_wgz1l0.jpg",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796448/IMG-20190808-WA0014_qjgw7p.jpg",
        isPublic: true,
      },
      {
        score: 7.5,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796448/IMG-20190808-WA0011_xttgjx.jpg",
        isPublic: true,
      },
      {
        score: 7.5,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796447/IMG-20190808-WA0007_ob0uvi.jpg",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796447/IMG-20190808-WA0002_v8wzuk.jpg",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796447/IMG-20190808-WA0006_fee7x2.jpg",
        isPublic: true,
      },
      {
        score: 7.5,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796447/IMG-20190808-WA0005_zc5jjw.jpg",
        isPublic: true,
      },
      {
        score: 8.0,
        caption: "",
        src: "https://res.cloudinary.com/busybenson/image/upload/v1590796447/IMG-20190808-WA0004_fbi1wa.jpg",
        isPublic: true,
      },
    ],
    videos: [
      {
        src: "https://youtu.be/KPV3orfWblk",
        title: "Elizabeth scored 8.0 at first attempt",
        isPublic: true,
      },
    ],
  },
  status: "",
  offers: [
    {
      type: "exam",
      name: "Pre-assessment test",
      description: "We administer a diagnostic test at the start of lessons.",
      discount: 0,
      amount: 0,
      group: 0,
      image: "",
    },
    {
      type: "discount",
      name: "Group discount",
      description: "Get discount when you book for 2 or more students",
      discount: 10,
      amount: 0,
      group: 2,
      image: "",
    },
    {
      type: "presentation",
      name: "Bonus session",
      description: "Attend a free session on Canada Immigration process",
      discount: 0,
      amount: 0,
      group: 0,
      image: "",
    },
    {
      type: "materials",
      name: "Learning materials",
      description: "Students receive e-copies of relevant study materials",
      discount: 0,
      amount: 0,
      group: 0,
      image: "",
    },
  ],
  faq: [
    {
      question: "What is IELTS and why do I need it?",
      answer:
        "It's an International English Language Test that is often required by organizations or embassies in the UK, USA, Canada, Australia, Ireland and New Zealand when you're looking to study in, work in or migrate to any of these countries. IELTS Academic is used for admissions, IELTS General Training is used for immigration or work, while UKVI is used when migrating to the UK.",
    },
    {
      question: "Do you cover Academic and General Training tests?",
      answer:
        "Yes, the class covers both Academic and General Training tests. The Speaking and Listening sections in both tests are the same, while the Reading and Writing modules are a bit different. This distinction in the Writing tasks and Reading texts are taught in class and students are made to practice based on which test they're sitting.",
    },
    {
      question: "Is there provision for makeup lessons?",
      answer:
        "Sadly, we can’t accommodate makeup lessons. If you miss a lesson, we recommend scheduling a private tutoring session with the teacher to cover the missed material.",
    },
    {
      question: "Can I cancel or reschedule a class?",
      answer:
        "You can cancel at least 1 week before lessons start and get a full refund. Please note that you cannot cancel or reschedule once lessons have commenced. You will not be refunded any cancelation after lessons have started.",
    },
    {
      question: "How does payment work?",
      answer:
        "Full payment is required before your slot can be confirmed in the class. Once a class is filled up, we automatically close registration for that class. You can pay online or by bank transfer.",
    },
    {
      question: "Can I pay at the venue?",
      answer:
        "We do not accept payment at the venue. Payment must be made before the first lesson. This is to ensure that we make adequate plans for every student we're expecting in class.",
    },
  ],
};

export const IELTSClasses = [
  {
    classID: "IELTSWeekend01",
    name: "Ikeja November Weekend Class",
    startDate: "2020-11-14T10:00:00",
    endDate: "2020-12-13T14:00:00",
    lessonDays: ["Saturday", "Sunday"],
    classChat: {
      general: {
        medium: "Whatsapp",
        link: "https://chat.whatsapp.com/Jf6Rj2290dKGpirAioJYEB",
      },
    },
    tutors: [
      {
        tutorId: "chidiebere01",
        name: "Chidiebere",
        headline: "Top-Rated English and IELTS Teacher for 8+ Years",
        lessonIndex: [0, 1, 2, 3, 4, 6, 8, 11],
        description:
          "Teaching the English Language is what I do best. For more than 8 years, I have taught numerous students preparing for IELTS, Cambridge and SAT who got admitted into their desired schools abroad or successfully migrated to the UK, US, Canada, New Zealand, Australia etc.\nMy lessons are personalized to reflect my students' interests, enhance their strengths, and minimize their weaknesses to ensure they have the confidence needed to pass the test. I teach all modules of the IELTS excellently, and go behold to improve my students' overall mastery of the English Language.\nHaving taught IELTS for so many years, I know what is takes to score a 7.0 - 9.0 bands in each module of the test; and that is what I teach my students.",
        photo:
          "https://res.cloudinary.com/busybenson/image/upload/v1590653442/Chidiebere_n5txfb.jpg",
        rating: 4.9,
        reviews: 24,
        lessons: 656,
        level: "premium",
      },
      {
        tutorId: "adeyinka01",
        name: "Adeyinka",
        headline: "Experienced & Top-Rated IELTS Tutor",
        lessonIndex: [5, 7, 9, 10],
        description:
          "I have an M.A. in English Language, and for over 6 years, I've helped hundreds of people pass the IELTS with bandscores of 7.0 - 9.0 who are now schooling or living abroad. I teach the four modules in IELTS General and Academic i.e. Writing, Speaking, Listening and Reading with special insight into what the examiners look out for and how to answer questions in the most accurate way to ensure you achieve a high bandscore even if you're sitting the test for the first time or making a repeat attempt. My classes are intense with a lot of explanation, practice, support and feedback to build your confidence for the exam and help you get a high score.",
        photo:
          "https://images.ctfassets.net/tp6rlg4xcwsc/7EskJqeiT6y04I2IcY664U/0ddf00752a2c4f37c61660fcb1db2983/ADEYINKA.jpg",
        rating: 5.0,
        reviews: 20,
        lessons: 408,
        level: "premium",
      },
    ],
    price: 35000,
    billingPeriod: "lifetime",
    earlybird: {},
    online: {},
    offline: {
      capacity: 20,
      registrations: 0,
      venue: {
        name: "Tuteria Learning Centre",
        address: "10 Bisi Olubi Street",
        vicinity: "Allen Avenue",
        region: "Ikeja",
        state: "Lagos",
        country: "Nigeria",
        capacity: 25,
      },
    },
    testimonials: [
      {
        photo: "",
        firstName: "Olajide",
        lastName: "Samuel",
        userId: "ID12354",
        review:
          "I can only say that based on my experience with Tuteria, I would recommend you guys again, again and again. I have had IELTS lesson in 2 different places before I came here and I can boldly beat my chest and say Tuteria is second to NONE. Thanks for the awesome experience!",
        reviewDate: "2020-05-02T18:18:10",
        photoUpload: [
          "https://res.cloudinary.com/busybenson/image/upload/v1590889866/IELTS%20Photos/IMG-20200530-WA0087_a1f5xd.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889858/IELTS%20Photos/IMG-20200530-WA0073_v9byze.jpg",
        ],
        rating: 5,
        region: "Surulere",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Emmanuella",
        lastName: "Anani",
        userId: "ID12654",
        review:
          "The class was quite insightful and impactful. I really had a wonderful time with my Tutor as he takes time to explain in-depth and sees that everyone participates actively in class. I am satisfied with the service offered and I urge our Tutor to keep up the good job.",
        reviewDate: "2019-10-09T18:18:10",
        photoUpload: [
          "https://res.cloudinary.com/busybenson/image/upload/v1590889853/IELTS%20Photos/IMG-20200530-WA0050_rtwogb.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889857/IELTS%20Photos/IMG-20200530-WA0069_wogtp5.jpg",
        ],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Tunji",
        lastName: "Samuel",
        userId: "ID12354",
        review:
          "Classes were awesome, interaction among students was efficient and seamless; especially during the group work supervised by our tutor. Also, kudos to the management for ensuring classes were adequate classes and provision was made for those who missed the classes to be catered for. I also liked the free Canadian Immigration class, it really enlightened me on how to go about the whole thing.",
        reviewDate: "2019-06-02T18:18:10",
        photoUpload: [
          "https://res.cloudinary.com/busybenson/image/upload/v1590889855/IELTS%20Photos/IMG-20200530-WA0065_wcldi1.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889861/IELTS%20Photos/IMG-20200530-WA0084_ps3cqq.jpg",
        ],
        rating: 5,
        region: "Surulere",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Gozie",
        lastName: "Uzu",
        userId: "ID12654",
        review:
          "He was excellent in delivering the IELTS lectures. I really understood every point within a short duration.",
        reviewDate: "2019-04-09T18:18:10",
        photoUpload: [
          "https://res.cloudinary.com/busybenson/image/upload/v1590889854/IELTS%20Photos/IMG-20200530-WA0042_hbxbws.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889843/IELTS%20Photos/IMG-20200530-WA0030_exnah3.jpg",
        ],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Olufunke",
        lastName: "Morayo",
        userId: "ID12354",
        review:
          "The lectures were all impressive! I never thought we could cover that much within a short time. The lessons made me understand all four aspects of IELTS very well. It was great having him as my tutor. Super lectures delivered!.",
        reviewDate: "2019-05-27T18:18:10",
        photoUpload: [
          "https://res.cloudinary.com/busybenson/image/upload/v1590889845/IELTS%20Photos/IMG-20200530-WA0025_rxdsul.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889845/IELTS%20Photos/IMG-20200530-WA0001_ajgrvd.jpg",
        ],
        rating: 5,
        region: "Surulere",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Ann",
        lastName: "Sandra",
        userId: "ID12654",
        review:
          "Tuteria Tutors are good! I must give that to you guys! I now have a better understanding of what is required to make better scores in my next ielts exam. I would mention the tutors alongside my recommendation to Tuteria with full confidence knowing that they will deliver.",
        reviewDate: "2019-06-01T18:18:10",
        photoUpload: [
          "https://res.cloudinary.com/busybenson/image/upload/v1590889847/IELTS%20Photos/IMG-20200530-WA0045_npzl33.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889846/IELTS%20Photos/IMG-20200530-WA0037_zxuyed.jpg",
        ],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Bolanle",
        lastName: "Adegoke",
        userId: "ID12354",
        review:
          "My friends discouraged me about taking lessons for IELTS, but I’m glad I did! Adeyinka and Chidi made me understand the techniques, rules and everything to pass the exam. They are good and very experienced teacher. I'd recommend this class to anyone serious about passing IELTS.",
        reviewDate: "2020-02-27T18:18:10",
        photoUpload: [
          "https://res.cloudinary.com/busybenson/image/upload/v1590889848/IELTS%20Photos/IMG-20200530-WA0026_cakexf.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889851/IELTS%20Photos/IMG-20200530-WA0057_xerigv.jpg",
        ],
        rating: 5,
        region: "Surulere",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Shonibare",
        lastName: "Ajayi",
        userId: "ID12654",
        review:
          "Pleased with everything. Very stimulating lectures and brilliantly taught. The lecturer's teaching is well organized and presented, which helped me to accept the new knowledge quickly. Great lectures. Energetic. Great structure. Thank You for everything!",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [
          "https://res.cloudinary.com/busybenson/image/upload/v1590889861/IELTS%20Photos/IMG-20200530-WA0039_obitsw.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889863/IELTS%20Photos/IMG-20200530-WA0081_gc3egk.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889862/IELTS%20Photos/IMG-20200530-WA0088_iwncsp.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889845/IELTS%20Photos/IMG-20200530-WA0019_nde5kv.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889850/IELTS%20Photos/IMG-20200530-WA0040_ngix1a.jpg",
          "https://res.cloudinary.com/busybenson/image/upload/v1590889853/IELTS%20Photos/IMG-20200530-WA0058_jpperh.jpg",
        ],
        rating: 4,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Emeka",
        lastName: "Samuel",
        userId: "ID12354",
        review:
          "I liked the lessons so much, there was so much to be covered and the tutor was so helpful. Very detailed. I'll recommended it to anyone looking for IELTS lessons in Lagos.",
        reviewDate: "2020-02-27T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Surulere",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Sandra",
        lastName: "Anani",
        userId: "ID12654",
        review:
          "It was a time fulfillment lesson and am happy i did attend Tuteria. Mr Adeyinka was in charge of my class, and he is a good tutor which I will recommend anytime and any day",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Akinola",
        lastName: "Rotimi",
        userId: "ID12654",
        review:
          "Tuteria has very sound IELTS tutors, with proper understanding of the four basic skills. He was able to provide in depth knowledge of the course within a short time frame. He was able to proffer solutions to help me achieve a better result.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Morenike",
        lastName: "Lawal",
        userId: "ID12654",
        review:
          "I have improved a lot since the lessons. I feel ready to take the test now. Thank you Adeyinka! I would recommend you and Tuteria's lessons to all other prospects! I don't even think there's any class out there that's up Tuteria's standard.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Immanuella",
        lastName: "Timothy",
        userId: "ID12654",
        review:
          "I’m happy I had the lessons. One thing that the lessons with Chidebere achieved was boosting my confidence. I was also made aware of the tips and tricks to do well in the exam. He’s very good. I will recommend him to anyone who wants to achieve a high band score.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Ogundipe",
        lastName: "Tunde",
        userId: "ID12654",
        review:
          "The delivery was excellent. The methodology was perfect. I have recommended and will would surely recommend Tuteria to all my friends.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Akinola",
        lastName: "Thompson",
        userId: "ID12654",
        review: "Adeyinka has a very good understanding of English.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 4,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Ayeteru",
        lastName: "Shogbamu",
        userId: "ID12654",
        review:
          "Nice experience with your company and especially Mr Adeyinka a great teacher.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Okoro",
        lastName: "Ezekiel",
        userId: "ID12654",
        review:
          "I will highly recommend Tuteria and Chidiebere for IELTS lessons because the teacher is well experienced in teaching English and IELTS, and the lessons are well planned.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Chekwube",
        lastName: "Elijah",
        userId: "ID12654",
        review:
          "Great tutor! He is someone that is more concerned about the success of his students than the money. He is highly recommended.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Adebimpe",
        lastName: "Isaiah",
        userId: "ID12654",
        review:
          "My teacher really knows IELTS very well, he's not joking! I would definitely recommend him. The overall lessons were intense. I started getting better from the first class.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Taiwo",
        lastName: "Israel",
        userId: "ID12654",
        review:
          "The teachers are really good in teaching and mentoring. Throughout the lessons, they provided us with detailed instructions, proper supervision, constructive feedback and warm encouragement. I will always be grateful for their support.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Madueke",
        lastName: "Echesi",
        userId: "ID12654",
        review:
          "The organization of the class was perfect. It was a wonderful experience at Tuteria. Lessons were very impactful. Both the tutor and staff are great and approachable. ",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Tolupe",
        lastName: "Ademola",
        userId: "ID12654",
        review:
          "Great value for money! I've never been this confident about passing IELTS",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Shalewa",
        lastName: "Olanike",
        userId: "ID12654",
        review:
          "Tuteria's tutors are very knowledgeable & teach with a lot of practical examples. The class was very well delivered. Quite commendable. ",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Ebimoboere",
        lastName: "Ayeni",
        userId: "ID12654",
        review:
          "5 star is not enough to describe my experience. Wish I could rate more than 5!",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Olanike",
        lastName: "Babatunde",
        userId: "ID12654",
        review:
          "I feel we needed more time to really go over the concepts taught, but I was happy that the teacher spotted that I was having challenges, and he made out time to help me.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Yemi",
        lastName: "Olamide",
        userId: "ID12654",
        review:
          "Tuteria is just awesome. The Mock exam, lectures, assistance was top-notch.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Victoria",
        lastName: "Sunday",
        userId: "ID12654",
        review:
          "My teacher was really good. I understood the lessons very well, and I hope to pass with a high mark and make him proud.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Babatunde",
        lastName: "Ismael",
        userId: "ID12654",
        review:
          "You guys are doing well. The classes and teachers were very impressive.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Aderonke",
        lastName: "Olajide",
        userId: "ID12654",
        review:
          "This class was beyond my expectation. It was sufficiently intense, yet moved at a very good pace for me. I'm very confident about passing IELTS this time.",
        reviewDate: "2019-05-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Uwemdimo",
        lastName: "Aniefiok",
        userId: "ID12654",
        review:
          "Keep up the great work Tuteria. I learnt so much. I'm ready to take on the exam now",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Abraham",
        lastName: "Olanipekun",
        userId: "ID12654",
        review:
          "Time and money was well spent. I'm very impressed, I learnt a great deal.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
      {
        photo: "",
        firstName: "Jubril",
        lastName: "Hammeed",
        userId: "ID12654",
        review:
          "I'm usually skeptical of companies who claim to offer IELTS lessons, I've attended 3 before and didn't gain much. Tuteria is different. I wasn't expecting much, but I was immensely surprised. I think everyone taking IELTS should come for your classes. It's the best.",
        reviewDate: "2019-01-01T18:18:10",
        photoUpload: [],
        rating: 5,
        region: "Ikoyi",
        state: "Lagos",
        country: "Nigeria",
        response: {},
      },
    ],
  },
  {
    classID: "IELTSWeekend02",
    name: "Gbagada November Weekend Class",
    startDate: "2020-11-14T10:00:00",
    endDate: "2020-12-13T14:00:00",
    lessonDays: ["Saturday", "Sunday"],
    classChat: {
      general: {
        medium: "Whatsapp",
        link: "https://chat.whatsapp.com/KQ7QROiDDaZ94H5F1xxHNc",
      },
    },
    tutors: [
      {
        tutorId: "adeyinka01",
        name: "Adeyinka",
        headline: "Experienced & Top-Rated IELTS Tutor",
        lessonIndex: [0, 1, 2, 3, 4, 6, 8, 11],
        description:
          "I have an M.A. in English Language, and for over 6 years, I've helped hundreds of people pass the IELTS with bandscores of 7.0 - 9.0 who are now schooling or living abroad. I teach the four modules in IELTS General and Academic i.e. Writing, Speaking, Listening and Reading with special insight into what the examiners look out for and how to answer questions in the most accurate way to ensure you achieve a high bandscore even if you're sitting the test for the first time or making a repeat attempt. My classes are intense with a lot of explanation, practice, support and feedback to build your confidence for the exam and help you get a high score.",
        photo:
          "https://images.ctfassets.net/tp6rlg4xcwsc/7EskJqeiT6y04I2IcY664U/0ddf00752a2c4f37c61660fcb1db2983/ADEYINKA.jpg",
        rating: 5.0,
        reviews: 20,
        lessons: 408,
        level: "premium",
      },
      {
        tutorId: "chidiebere01",
        name: "Chidiebere",
        headline: "Top-Rated English and IELTS Teacher for 8+ Years",
        lessonIndex: [5, 7, 9, 10],
        description:
          "Teaching the English Language is what I do best. For more than 8 years, I have taught numerous students preparing for IELTS, Cambridge and SAT who got admitted into their desired schools abroad or successfully migrated to the UK, US, Canada, New Zealand, Australia etc.\nMy lessons are personalized to reflect my students' interests, enhance their strengths, and minimize their weaknesses to ensure they have the confidence needed to pass the test. I teach all modules of the IELTS excellently, and go behold to improve my students' overall mastery of the English Language.\nHaving taught IELTS for so many years, I know what is takes to score a 7.0 - 9.0 bands in each module of the test; and that is what I teach my students.",
        photo:
          "https://res.cloudinary.com/busybenson/image/upload/v1590653442/Chidiebere_n5txfb.jpg",
        rating: 4.9,
        reviews: 24,
        lessons: 656,
        level: "premium",
      },
    ],
    price: 35000,
    billingPeriod: "lifetime",
    earlybird: {},
    online: {},
    offline: {
      capacity: 15,
      registrations: 0,
      venue: {
        name: "Tuteria Learning Centre",
        address: "10 Lanre Awolokun Street",
        vicinity: "Gbagada Phase 2",
        region: "Gbagada",
        state: "Lagos",
        country: "Nigeria",
        capacity: 25,
      },
    },
    testimonials: [],
  },
  {
    classID: "IELTSOnline01",
    name: "Online June Evening Class",
    startDate: "2020-10-17T16:00:00",
    endDate: "2020-11-15T20:00:00",
    lessonDays: ["Tuesday", "Thursday"],
    classChat: {
      general: {
        medium: "Whatsapp",
        link: "https://chat.whatsapp.com/FVbWfyCIbJUKbZrPlC4eFC",
      },
    },
    tutors: [
      {
        tutorId: "chidiebere01",
        name: "Chidiebere",
        headline: "Top-Rated English and IELTS Teacher for 8+ Years",
        lessonIndex: [0, 1, 2, 3, 4, 6, 8, 11],
        description:
          "Teaching the English Language is what I do best. For more than 8 years, I have taught numerous students preparing for IELTS, Cambridge and SAT who got admitted into their desired schools abroad or successfully migrated to the UK, US, Canada, New Zealand, Australia etc.\nMy lessons are personalized to reflect my students' interests, enhance their strengths, and minimize their weaknesses to ensure they have the confidence needed to pass the test. I teach all modules of the IELTS excellently, and go behold to improve my students' overall mastery of the English Language.\nHaving taught IELTS for so many years, I know what is takes to score a 7.0 - 9.0 bands in each module of the test; and that is what I teach my students.",
        photo:
          "https://res.cloudinary.com/busybenson/image/upload/v1590653442/Chidiebere_n5txfb.jpg",
        rating: 4.9,
        reviews: 24,
        lessons: 656,
        level: "premium",
      },
      {
        tutorId: "adeyinka01",
        name: "Adeyinka",
        headline: "Experienced & Top-Rated IELTS Tutor",
        lessonIndex: [5, 7, 9, 10],
        description:
          "I have an M.A. in English Language, and for over 6 years, I've helped hundreds of people pass the IELTS with bandscores of 7.0 - 9.0 who are now schooling or living abroad. I teach the four modules in IELTS General and Academic i.e. Writing, Speaking, Listening and Reading with special insight into what the examiners look out for and how to answer questions in the most accurate way to ensure you achieve a high bandscore even if you're sitting the test for the first time or making a repeat attempt. My classes are intense with a lot of explanation, practice, support and feedback to build your confidence for the exam and help you get a high score.",
        photo:
          "https://images.ctfassets.net/tp6rlg4xcwsc/7EskJqeiT6y04I2IcY664U/0ddf00752a2c4f37c61660fcb1db2983/ADEYINKA.jpg",
        rating: 5.0,
        reviews: 20,
        lessons: 408,
        level: "premium",
      },
    ],
    price: 20000,
    billingPeriod: "lifetime",
    earlybird: {},
    online: {
      capacity: 50,
      registrations: 0,
    },
    offline: {},
    testimonials: [],
  },
  {
    classID: "IELTSWeekday01",
    name: "Ikeja November Weekday Class",
    startDate: "2020-11-02T10:00:00",
    endDate: "2020-11-27T14:00:00",
    lessonDays: ["Monday", "Wednesday", "Friday"],
    classChat: {
      general: {
        medium: "Whatsapp",
        link: "https://chat.whatsapp.com/BGEzZBJpTByGCkXoYZu1WN",
      },
    },
    tutors: [
      {
        tutorId: "chidiebere01",
        name: "Chidiebere",
        headline: "Top-Rated English and IELTS Teacher for 8+ Years",
        lessonIndex: [0, 1, 2, 3, 4, 6, 8, 11],
        description:
          "Teaching the English Language is what I do best. For more than 8 years, I have taught numerous students preparing for IELTS, Cambridge and SAT who got admitted into their desired schools abroad or successfully migrated to the UK, US, Canada, New Zealand, Australia etc.\nMy lessons are personalized to reflect my students' interests, enhance their strengths, and minimize their weaknesses to ensure they have the confidence needed to pass the test. I teach all modules of the IELTS excellently, and go behold to improve my students' overall mastery of the English Language.\nHaving taught IELTS for so many years, I know what is takes to score a 7.0 - 9.0 bands in each module of the test; and that is what I teach my students.",
        photo:
          "https://res.cloudinary.com/busybenson/image/upload/v1590653442/Chidiebere_n5txfb.jpg",
        rating: 4.9,
        reviews: 24,
        lessons: 656,
        level: "premium",
      },
      {
        tutorId: "adeyinka01",
        name: "Adeyinka",
        headline: "Experienced & Top-Rated IELTS Tutor",
        lessonIndex: [5, 7, 9, 10],
        description:
          "I have an M.A. in English Language, and for over 6 years, I've helped hundreds of people pass the IELTS with bandscores of 7.0 - 9.0 who are now schooling or living abroad. I teach the four modules in IELTS General and Academic i.e. Writing, Speaking, Listening and Reading with special insight into what the examiners look out for and how to answer questions in the most accurate way to ensure you achieve a high bandscore even if you're sitting the test for the first time or making a repeat attempt. My classes are intense with a lot of explanation, practice, support and feedback to build your confidence for the exam and help you get a high score.",
        photo:
          "https://images.ctfassets.net/tp6rlg4xcwsc/7EskJqeiT6y04I2IcY664U/0ddf00752a2c4f37c61660fcb1db2983/ADEYINKA.jpg",
        rating: 5.0,
        reviews: 20,
        lessons: 408,
        level: "premium",
      },
    ],
    price: 35000,
    billingPeriod: "lifetime",
    earlybird: {},
    online: {},
    offline: {
      capacity: 20,
      registrations: 0,
      venue: {
        name: "Tuteria Learning Centre",
        address: "10 Bisi Olubi Street",
        vicinity: "Allen Avenue",
        region: "Ikeja",
        state: "Lagos",
        country: "Nigeria",
        capacity: 25,
      },
    },
    testimonials: [],
  },
  {
    classID: "IELTSWeekday02",
    name: "Gbagada November Weekday Class",
    startDate: "2020-11-02T10:00:00",
    endDate: "2020-11-27T14:00:00",
    lessonDays: ["Monday", "Wednesday", "Friday"],
    classChat: {
      general: {
        medium: "Whatsapp",
        link: "https://chat.whatsapp.com/GpCV87fVMDTFE7ryVzRSD2",
      },
    },
    tutors: [
      {
        tutorId: "adeyinka01",
        name: "Adeyinka",
        headline: "Experienced & Top-Rated IELTS Tutor",
        lessonIndex: [0, 1, 2, 3, 4, 6, 8, 11],
        description:
          "I have an M.A. in English Language, and for over 6 years, I've helped hundreds of people pass the IELTS with bandscores of 7.0 - 9.0 who are now schooling or living abroad. I teach the four modules in IELTS General and Academic i.e. Writing, Speaking, Listening and Reading with special insight into what the examiners look out for and how to answer questions in the most accurate way to ensure you achieve a high bandscore even if you're sitting the test for the first time or making a repeat attempt. My classes are intense with a lot of explanation, practice, support and feedback to build your confidence for the exam and help you get a high score.",
        photo:
          "https://images.ctfassets.net/tp6rlg4xcwsc/7EskJqeiT6y04I2IcY664U/0ddf00752a2c4f37c61660fcb1db2983/ADEYINKA.jpg",
        rating: 5.0,
        reviews: 20,
        lessons: 408,
        level: "premium",
      },
      {
        tutorId: "chidiebere01",
        name: "Chidiebere",
        headline: "Top-Rated English and IELTS Teacher for 8+ Years",
        lessonIndex: [5, 7, 9, 10],
        description:
          "Teaching the English Language is what I do best. For more than 8 years, I have taught numerous students preparing for IELTS, Cambridge and SAT who got admitted into their desired schools abroad or successfully migrated to the UK, US, Canada, New Zealand, Australia etc.\nMy lessons are personalized to reflect my students' interests, enhance their strengths, and minimize their weaknesses to ensure they have the confidence needed to pass the test. I teach all modules of the IELTS excellently, and go behold to improve my students' overall mastery of the English Language.\nHaving taught IELTS for so many years, I know what is takes to score a 7.0 - 9.0 bands in each module of the test; and that is what I teach my students.",
        photo:
          "https://res.cloudinary.com/busybenson/image/upload/v1590653442/Chidiebere_n5txfb.jpg",
        rating: 4.9,
        reviews: 24,
        lessons: 656,
        level: "premium",
      },
    ],
    price: 35000,
    billingPeriod: "lifetime",
    earlybird: {},
    online: {},
    offline: {
      capacity: 15,
      registrations: 0,
      venue: {
        name: "Tuteria Learning Centre",
        address: "10 Lanre Awolokun Street",
        vicinity: "Gbagada Phase 2",
        region: "Gbagada",
        state: "Lagos",
        country: "Nigeria",
        capacity: 25,
      },
    },
    testimonials: [],
  },
  {
    classID: "IELTSWeekend05",
    name: "Abuja November Weekend Class",
    startDate: "2020-11-14T10:00:00",
    endDate: "2020-12-13T14:00:00",
    lessonDays: ["Saturday", "Sunday"],
    classChat: {
      general: {
        medium: "Whatsapp",
        link: "https://chat.whatsapp.com/KQ7QROiDDaZ94H5F1xxHNc",
      },
    },
    tutors: [
      {
        tutorId: "adeyinka01",
        name: "Adeyinka",
        headline: "Experienced & Top-Rated IELTS Tutor",
        lessonIndex: [0, 1, 2, 3, 4, 6, 8, 11],
        description:
          "I have an M.A. in English Language, and for over 6 years, I've helped hundreds of people pass the IELTS with bandscores of 7.0 - 9.0 who are now schooling or living abroad. I teach the four modules in IELTS General and Academic i.e. Writing, Speaking, Listening and Reading with special insight into what the examiners look out for and how to answer questions in the most accurate way to ensure you achieve a high bandscore even if you're sitting the test for the first time or making a repeat attempt. My classes are intense with a lot of explanation, practice, support and feedback to build your confidence for the exam and help you get a high score.",
        photo:
          "https://images.ctfassets.net/tp6rlg4xcwsc/7EskJqeiT6y04I2IcY664U/0ddf00752a2c4f37c61660fcb1db2983/ADEYINKA.jpg",
        rating: 5.0,
        reviews: 20,
        lessons: 408,
        level: "premium",
      },
      {
        tutorId: "chidiebere01",
        name: "Chidiebere",
        headline: "Top-Rated English and IELTS Teacher for 8+ Years",
        lessonIndex: [5, 7, 9, 10],
        description:
          "Teaching the English Language is what I do best. For more than 8 years, I have taught numerous students preparing for IELTS, Cambridge and SAT who got admitted into their desired schools abroad or successfully migrated to the UK, US, Canada, New Zealand, Australia etc.\nMy lessons are personalized to reflect my students' interests, enhance their strengths, and minimize their weaknesses to ensure they have the confidence needed to pass the test. I teach all modules of the IELTS excellently, and go behold to improve my students' overall mastery of the English Language.\nHaving taught IELTS for so many years, I know what is takes to score a 7.0 - 9.0 bands in each module of the test; and that is what I teach my students.",
        photo:
          "https://res.cloudinary.com/busybenson/image/upload/v1590653442/Chidiebere_n5txfb.jpg",
        rating: 4.9,
        reviews: 24,
        lessons: 656,
        level: "premium",
      },
    ],
    price: 40000,
    billingPeriod: "lifetime",
    earlybird: {},
    online: {},
    offline: {
      capacity: 30,
      registrations: 0,
      venue: {
        name: "Seedbuilders Hub",
        address: "6A Embu street",
        vicinity: "Amino Kano",
        region: "Wuse 2",
        state: "Abuja",
        country: "Nigeria",
        capacity: 40,
      },
    },
    testimonials: [],
  },
];
